// ONE-TIME MIGRATION SCRIPT — kept for provenance, no longer runnable as-is.
//
// This generated db/seed.sql and src/content/fallback.json from the content that
// used to be hardcoded in the six src/pages/*Project.jsx files. Those files were
// replaced by the data-driven src/pages/ProjectPage.jsx, so running this now
// will fail on the missing sources; recover them from git history first if you
// ever need to regenerate.
//
// To refresh the fallback snapshot going forward, use `npm run snapshot`.
import { readFileSync, writeFileSync } from 'node:fs';

const read = (p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const q = (v) =>
  v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const webp = (jpg) => (jpg ? jpg.replace(/\.(jpe?g)$/i, '.webp') : null);

// Collapse a JSX text block into a single normalised paragraph.
const squash = (s) => s.replace(/\s+/g, ' ').trim();

const PAGES = [
  { file: 'FashionProject',      slug: 'fashion-project',       sort: 2, kind: 'photo', cover: '/photos/reelphotos/mari7.jpg', workDesc: 'COLLECTIONS: 4' },
  { file: 'PortraitProject',     slug: 'portrait-project',      sort: 1, kind: 'photo', cover: '/photos/reelphotos/mari6.jpg', workDesc: 'COLLECTIONS: 8' },
  { file: 'LightProject',        slug: 'light-project',         sort: 3, kind: 'photo', cover: '/photos/Light/Light.jpg', workDesc: 'COLLECTIONS: 3' },
  { file: 'FineartProject',      slug: 'fineart-project',       sort: 4, kind: 'photo', cover: '/photos/Fineart/Fineart.jpg', workDesc: 'COLLECTIONS: 2' },
  { file: 'UrbangeometryProject',slug: 'urbangeometry-project', sort: 5, kind: 'photo', cover: '/photos/Urbangeometry/Urbangeometry.jpg', workDesc: 'COLLECTIONS: 2' },
  { file: 'VideographyProject',  slug: 'videography-project',   sort: 6, kind: 'video', cover: '/photos/Videography/videography.jpg', workDesc: 'COLLECTIONS: 3' },
];

const manifest = { projects: [], reel: [] };

const out = [
  '-- Generated by db/generate-seed.mjs from the hardcoded content in src/.',
  '-- Run AFTER schema.sql. Idempotent: safe to re-run.',
  '',
  'begin;',
  '',
];

for (const p of PAGES) {
  const src = read(`src/pages/${p.file}.jsx`);

  const title = /<S\.ProjectTitle\b[\s\S]*?>([\s\S]*?)<\/S\.ProjectTitle>/.exec(src)[1].trim();
  const props = Object.fromEntries(
    [...(/<S\.ProjectTitle\b([\s\S]*?)>/.exec(src)[1]).matchAll(/\$(\w+)="([^"]*)"/g)]
      .map((m) => [m[1], m[2]])
  );
  delete props.isVisible;

  const countLabel = squash(/<S\.DateText>([\s\S]*?)<\/S\.DateText>/.exec(src)[1]);
  const body = squash(/<S\.BodyText\b[\s\S]*?>([\s\S]*?)<\/S\.BodyText>/.exec(src)[1]);
  const hero = /<S\.HeroImage[\s\S]*?src="([^"]+)"/.exec(src)[1];

  out.push(
    `-- ${title}`,
    `insert into projects (slug, title, description, count_label, body_text, hero_jpg, hero_webp, cover_jpg, cover_webp, title_offset, media_kind, sort_order, published)`,
    `values (${q(p.slug)}, ${q(title)}, ${q(p.workDesc)}, ${q(countLabel)}, ${q(body)},`,
    `        ${q(hero)}, ${q(webp(hero))}, ${q(p.cover)}, ${q(webp(p.cover))},`,
    `        ${q(JSON.stringify(props))}::jsonb, ${q(p.kind)}, ${p.sort}, true)`,
    `on conflict (slug) do nothing;`,
    ''
  );

  // Gallery items: photo URLs, or YouTube ids for the video project.
  const galleryBlock = /galleryImages\s*=\s*\[([\s\S]*?)\]/.exec(src);
  const items = [];
  if (galleryBlock) {
    for (const m of galleryBlock[1].matchAll(/'([^']+)'/g)) items.push({ jpg: m[1] });
  }
  const videoBlock = /youtubeVideos\s*=\s*\[([\s\S]*?)\]/.exec(src);
  if (videoBlock) {
    for (const m of videoBlock[1].matchAll(/id:\s*'([^']+)'/g)) items.push({ youtube: m[1] });
  }

  manifest.projects.push({
    slug: p.slug,
    title,
    description: p.workDesc,
    countLabel,
    bodyText: body,
    hero: { jpg: hero, webp: webp(hero) },
    cover: { jpg: p.cover, webp: webp(p.cover) },
    titleOffset: props,
    mediaKind: p.kind,
    photos: items.map((it, i) => ({
      jpg: it.jpg ?? null,
      webp: webp(it.jpg ?? null),
      youtubeId: it.youtube ?? null,
      alt: `${title} ${i + 1}`,
      width: null,
      height: null,
    })),
  });

  items.forEach((it, i) => {
    const alt = `${title} ${i + 1}`;
    out.push(
      `insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)`,
      `select id, ${q(it.jpg ?? null)}, ${q(webp(it.jpg ?? null))}, ${q(it.youtube ?? null)}, ${q(alt)}, ${i}`,
      `from projects where slug = ${q(p.slug)}`,
      `and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = ${i});`
    );
  });
  out.push('');
}

// ------------------------------------------------------------------- reel ---
const reelSrc = read('src/components/Reel.jsx');
const reelImages = [...(/const images = \[([\s\S]*?)\];/.exec(reelSrc)[1]).matchAll(/\{\s*id:\s*(\d+),\s*src:\s*'([^']+)'\s*\}/g)]
  .map((m) => ({ id: Number(m[1]), src: m[2] }));

const navBlock = /const navigationMap = \{([\s\S]*?)\n\};/.exec(reelSrc)[1];
const nav = {};
for (const line of navBlock.split('\n')) {
  const m = /^\s*(\d+):\s*\{(.*)\},?\s*$/.exec(line);
  if (!m) continue;
  const inner = m[2];
  // Titles in navigationMap use single OR double quotes (apostrophes force the latter).
  const pick = (k) => {
    const r = new RegExp(`${k}:\\s*(['"])((?:(?!\\1).)*)\\1`).exec(inner);
    return r ? r[2] : null;
  };
  const idx = /photoIndex:\s*(\d+)/.exec(inner);
  nav[Number(m[1])] = {
    route: pick('route'),
    title: pick('title'),
    caption: pick('caption'),
    photoIndex: idx ? Number(idx[1]) : null,
  };
}

out.push('-- Home reel');
reelImages.forEach((img, i) => {
  const n = nav[img.id] ?? {};
  const slug = n.route ? n.route.replace('/work/', '') : null;
  // Reel.jsx renders every 8th frame narrow; with 8 items that is the last one.
  const isNarrow = (i + 1) % reelImages.length === 0;
  out.push(
    `insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)`,
    `select ${q(img.src)}, ${q(webp(img.src))}, ${q(n.title ?? '')}, ${q(n.caption ?? '')}, ${q(slug)}, ${n.photoIndex ?? 'null'}, ${isNarrow}, ${i}`,
    `where not exists (select 1 from reel_items where sort_order = ${i});`
  );
  manifest.reel.push({
    jpg: img.src,
    webp: webp(img.src),
    title: n.title ?? '',
    caption: n.caption ?? '',
    targetSlug: slug,
    targetPhotoIndex: n.photoIndex ?? null,
    isNarrow,
  });
});

out.push('', 'commit;', '');
writeFileSync(new URL('./seed.sql', import.meta.url), out.join('\n'));

// Shipped in the bundle so the site still renders correctly if /api/content is
// unreachable: Supabase down, env vars missing, or a deploy that lands before
// the migration has been run.
manifest.projects.sort((a, b) => {
  const order = new Map(PAGES.map((x) => [x.slug, x.sort]));
  return order.get(a.slug) - order.get(b.slug);
});
writeFileSync(
  new URL('../src/content/fallback.json', import.meta.url),
  JSON.stringify(manifest, null, 2) + '\n'
);
console.log(`seed.sql + src/content/fallback.json written — ${PAGES.length} projects, ${reelImages.length} reel items`);
