-- Full migration: schema + seed. Safe to re-run.

-- MariPortfolio admin schema
-- Run once in the Supabase SQL editor.
--
-- Security model: every table has RLS enabled with NO policies, so the public
-- anon key can read nothing. All access goes through the serverless functions
-- in /api using the service-role key, which bypasses RLS. The API is the only door.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- content ---

create table if not exists projects (
  id            uuid primary key default gen_random_uuid(),
  slug          text unique not null,
  title         text not null,
  description   text not null default '',   -- /work tile subtitle, e.g. "COLLECTIONS: 8"
  count_label   text not null default '',   -- project page label, e.g. "[ Photo Collections: 8 ]"
  body_text     text not null default '',
  hero_jpg      text,
  hero_webp     text,
  cover_jpg     text,                       -- tile shown on /work
  cover_webp    text,
  title_offset  jsonb not null default '{}'::jsonb, -- styled-components prop bag for the title
  media_kind    text not null default 'photo' check (media_kind in ('photo','video')),
  sort_order    int  not null default 0,
  published     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists photos (
  id          uuid primary key default gen_random_uuid(),
  project_id  uuid not null references projects(id) on delete cascade,
  youtube_id  text,                      -- set for video projects; url_jpg is null then
  url_jpg     text,
  url_webp    text,
  alt         text not null default '',
  width       int,
  height      int,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  constraint photos_has_media check (url_jpg is not null or youtube_id is not null)
);

create index if not exists photos_project_idx on photos(project_id, sort_order);

create table if not exists reel_items (
  id                 uuid primary key default gen_random_uuid(),
  url_jpg            text not null,
  url_webp           text,
  title              text not null default '',
  caption            text not null default '',
  target_slug        text,        -- project slug to navigate to on click
  target_photo_index int,         -- index within that project's gallery
  is_narrow          boolean not null default false, -- renders as a narrow frame
  sort_order         int not null default 0,
  created_at         timestamptz not null default now()
);

create index if not exists reel_order_idx on reel_items(sort_order);

-- ------------------------------------------------------------------ auth ---

create table if not exists admin_credentials (
  id            text primary key,           -- base64url credential ID
  public_key    text not null,              -- base64url; bytea does not round-trip via PostgREST
  counter       bigint not null default 0,
  transports    text[] not null default '{}',
  device_name   text not null default 'Unnamed device',
  created_at    timestamptz not null default now(),
  last_used_at  timestamptz
);

create table if not exists admin_invites (
  token_hash  text primary key,             -- sha256 of the one-time token
  label       text not null default '',
  expires_at  timestamptz not null,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);

-- --------------------------------------------------------------------- rls ---

alter table projects           enable row level security;
alter table photos             enable row level security;
alter table reel_items         enable row level security;
alter table admin_credentials  enable row level security;
alter table admin_invites      enable row level security;

-- Generated by db/generate-seed.mjs from the hardcoded content in src/.
-- Run AFTER schema.sql. Idempotent: safe to re-run.

begin;

-- Fashion
insert into projects (slug, title, description, count_label, body_text, hero_jpg, hero_webp, cover_jpg, cover_webp, title_offset, media_kind, sort_order, published)
values ('fashion-project', 'Fashion', 'COLLECTIONS: 4', '[ Photo Collections: 16 ]', 'My fashion photoshoots are intended to be styled and framed in ways that emulate a specific time period of fashion, industry, or lifestyle. The highlight of these photos is the clothing and accessories, but the models contribute to telling a story about the chosen aesthetic. Using technical skills, creative vision, elements like styling, location, and mood help elevate garments beyond mere products into encompassing a curated atmosphere/visual.',
        '/photos/Fashion/Fashion.jpg', '/photos/Fashion/Fashion.webp', '/photos/reelphotos/mari7.jpg', '/photos/reelphotos/mari7.webp',
        '{"left":"198px","leftXl":"150px","leftMd":"110px"}'::jsonb, 'photo', 2, true)
on conflict (slug) do nothing;

insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion1.jpg', '/photos/Fashion/Fashion1.webp', null, 'Fashion 1', 0
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 0);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion2.jpg', '/photos/Fashion/Fashion2.webp', null, 'Fashion 2', 1
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 1);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion3.jpg', '/photos/Fashion/Fashion3.webp', null, 'Fashion 3', 2
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 2);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion4.jpg', '/photos/Fashion/Fashion4.webp', null, 'Fashion 4', 3
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 3);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion5.jpg', '/photos/Fashion/Fashion5.webp', null, 'Fashion 5', 4
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 4);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion6.jpg', '/photos/Fashion/Fashion6.webp', null, 'Fashion 6', 5
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 5);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion7.jpg', '/photos/Fashion/Fashion7.webp', null, 'Fashion 7', 6
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 6);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion8.jpg', '/photos/Fashion/Fashion8.webp', null, 'Fashion 8', 7
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 7);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion9.jpg', '/photos/Fashion/Fashion9.webp', null, 'Fashion 9', 8
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 8);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion10.jpg', '/photos/Fashion/Fashion10.webp', null, 'Fashion 10', 9
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 9);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion11.jpg', '/photos/Fashion/Fashion11.webp', null, 'Fashion 11', 10
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 10);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion12.jpg', '/photos/Fashion/Fashion12.webp', null, 'Fashion 12', 11
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 11);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion13.jpg', '/photos/Fashion/Fashion13.webp', null, 'Fashion 13', 12
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 12);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion14.jpg', '/photos/Fashion/Fashion14.webp', null, 'Fashion 14', 13
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 13);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fashion/Fashion15.jpg', '/photos/Fashion/Fashion15.webp', null, 'Fashion 15', 14
from projects where slug = 'fashion-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 14);

-- Portraits
insert into projects (slug, title, description, count_label, body_text, hero_jpg, hero_webp, cover_jpg, cover_webp, title_offset, media_kind, sort_order, published)
values ('portrait-project', 'Portraits', 'COLLECTIONS: 8', '[ Photo Collections: 8 ]', 'This collection of portraits was meant to capture the ways I view my friends and their unique auras. I used a variety of portrait lighting techniques including split, loop, beauty, rembrandt, paramount, and short/broad light. Each of these techniques is used to accentuate the feelings each photo evokes. I work with my models to style and pose them in ways that align with their own personal image and simultaneously match the vision I conceptualized for the photograph.',
        '/photos/PortraitProject/Portrait.jpg', '/photos/PortraitProject/Portrait.webp', '/photos/reelphotos/mari6.jpg', '/photos/reelphotos/mari6.webp',
        '{"left":"198px","leftXl":"150px","leftMd":"110px"}'::jsonb, 'photo', 1, true)
on conflict (slug) do nothing;

insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/PortraitProject/Portrait1.jpg', '/photos/PortraitProject/Portrait1.webp', null, 'Portraits 1', 0
from projects where slug = 'portrait-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 0);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/PortraitProject/Portrait2.jpg', '/photos/PortraitProject/Portrait2.webp', null, 'Portraits 2', 1
from projects where slug = 'portrait-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 1);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/PortraitProject/Portrait3.jpg', '/photos/PortraitProject/Portrait3.webp', null, 'Portraits 3', 2
from projects where slug = 'portrait-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 2);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/PortraitProject/Portrait4.jpg', '/photos/PortraitProject/Portrait4.webp', null, 'Portraits 4', 3
from projects where slug = 'portrait-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 3);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/PortraitProject/Portrait5.jpg', '/photos/PortraitProject/Portrait5.webp', null, 'Portraits 5', 4
from projects where slug = 'portrait-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 4);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/PortraitProject/Portrait6.jpg', '/photos/PortraitProject/Portrait6.webp', null, 'Portraits 6', 5
from projects where slug = 'portrait-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 5);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/PortraitProject/Portrait7.jpg', '/photos/PortraitProject/Portrait7.webp', null, 'Portraits 7', 6
from projects where slug = 'portrait-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 6);

-- Light
insert into projects (slug, title, description, count_label, body_text, hero_jpg, hero_webp, cover_jpg, cover_webp, title_offset, media_kind, sort_order, published)
values ('light-project', 'Light', 'COLLECTIONS: 3', '[ Photo Collections: 4 ]', 'In this collection I used a photographic technique called painting with light. I used various light sources to illuminate parts of a scene during a long exposure. This method allows for the creation of unique light patterns, highlights, and artistic effects that are not possible with standard lighting techniques. A combination of gelled lights, external flash, and natural light was used to paint the photo interpretation of song lyrics I chose beforehand.',
        '/photos/Light/Light.jpg', '/photos/Light/Light.webp', '/photos/Light/Light.jpg', '/photos/Light/Light.webp',
        '{"left":"198px","leftXl":"150px","leftMd":"110px"}'::jsonb, 'photo', 3, true)
on conflict (slug) do nothing;

insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Light/Light1.jpg', '/photos/Light/Light1.webp', null, 'Light 1', 0
from projects where slug = 'light-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 0);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Light/Light2.jpg', '/photos/Light/Light2.webp', null, 'Light 2', 1
from projects where slug = 'light-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 1);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Light/Light3.jpg', '/photos/Light/Light3.webp', null, 'Light 3', 2
from projects where slug = 'light-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 2);

-- Fine Art
insert into projects (slug, title, description, count_label, body_text, hero_jpg, hero_webp, cover_jpg, cover_webp, title_offset, media_kind, sort_order, published)
values ('fineart-project', 'Fine Art', 'COLLECTIONS: 2', '[ Photo Collections: 2 ]', 'Creating and imagining stories before shooting was a vital part of this collection. Brainstorming for this included storyboarding and writing conceptual captions beforehand. These photos are meant to be interpreted abstractly with no clear answer for what is occurring in the photo. The audience should create their own story based on what is depicted in the image. The collection is meant to convey a sense of whimsy and appear as photos that could be found in storybooks.',
        '/photos/Fineart/Fineart.jpg', '/photos/Fineart/Fineart.webp', '/photos/Fineart/Fineart.jpg', '/photos/Fineart/Fineart.webp',
        '{"left":"198px","leftXl":"150px","leftMd":"110px"}'::jsonb, 'photo', 4, true)
on conflict (slug) do nothing;

insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Fineart/Fineart1.jpg', '/photos/Fineart/Fineart1.webp', null, 'Fine Art 1', 0
from projects where slug = 'fineart-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 0);

-- Urban Geometry
insert into projects (slug, title, description, count_label, body_text, hero_jpg, hero_webp, cover_jpg, cover_webp, title_offset, media_kind, sort_order, published)
values ('urbangeometry-project', 'Urban Geometry', 'COLLECTIONS: 2', '[ Photo Collections: 2 ]', 'This collection highlights the natural patterns that appear in urban settings. These photos focus on architectural design, negative space, and the harmony of the natural and man-made world. Perspective and framing is very important here as it can highlight symmetries and light and identify otherwise hidden textures or patterns.',
        '/photos/Urbangeometry/Urbangeometry.jpg', '/photos/Urbangeometry/Urbangeometry.webp', '/photos/Urbangeometry/Urbangeometry.jpg', '/photos/Urbangeometry/Urbangeometry.webp',
        '{"left":"80px","top":"80%","width":"900px","lineHeight":"0.65","leftXl":"150px","leftMd":"110px","fontSizeXs":"50px"}'::jsonb, 'photo', 5, true)
on conflict (slug) do nothing;

insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, '/photos/Urbangeometry/Urbangeometry1.jpg', '/photos/Urbangeometry/Urbangeometry1.webp', null, 'Urban Geometry 1', 0
from projects where slug = 'urbangeometry-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 0);

-- Videography
insert into projects (slug, title, description, count_label, body_text, hero_jpg, hero_webp, cover_jpg, cover_webp, title_offset, media_kind, sort_order, published)
values ('videography-project', 'Videography', 'COLLECTIONS: 3', '[ Photo Collections: 3 ]', 'My videography is often in collaboration with other artists to help portray their art visually. I attempt to capture the essence of artists'' music through video by using a variety of techniques, pacing, framing, editing, and even cameras. These videos are used for social media promotion and Spotify to appeal to audiences who may resonate with the video and feel more inclined to look into the associated music. My videography is also used to promote Cal Poly''s fashion club, FITS, and their related campaigns by using video to highlight clothing using a more fashion and lifestyle approach.',
        '/photos/Videography/videography.jpg', '/photos/Videography/videography.webp', '/photos/Videography/videography.jpg', '/photos/Videography/videography.webp',
        '{"left":"80px","leftXl":"150px","leftMd":"110px"}'::jsonb, 'video', 6, true)
on conflict (slug) do nothing;

insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, null, null, 'lakOaiXYcp4', 'Videography 1', 0
from projects where slug = 'videography-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 0);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, null, null, 'idLy5RoOYME', 'Videography 2', 1
from projects where slug = 'videography-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 1);
insert into photos (project_id, url_jpg, url_webp, youtube_id, alt, sort_order)
select id, null, null, 'ok38O_TNS0Q', 'Videography 3', 2
from projects where slug = 'videography-project'
and not exists (select 1 from photos p2 where p2.project_id = projects.id and p2.sort_order = 2);

-- Home reel
insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)
select '/photos/reelphotos/mari1.jpg', '/photos/reelphotos/mari1.webp', 'Heaven''s Playground', 'Fashion-Project', 'fashion-project', 5, false, 0
where not exists (select 1 from reel_items where sort_order = 0);
insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)
select '/photos/reelphotos/mari8.jpg', '/photos/reelphotos/mari8.webp', 'Breath of Winter', 'Portrait-Project', 'portrait-project', 1, false, 1
where not exists (select 1 from reel_items where sort_order = 1);
insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)
select '/photos/reelphotos/mari3.jpg', '/photos/reelphotos/mari3.webp', 'Rest Stop', 'Portrait-Project', 'portrait-project', 0, false, 2
where not exists (select 1 from reel_items where sort_order = 2);
insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)
select '/photos/reelphotos/mari4.jpg', '/photos/reelphotos/mari4.webp', 'Headin'' South', 'Fashion-Project', 'fashion-project', 7, false, 3
where not exists (select 1 from reel_items where sort_order = 3);
insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)
select '/photos/reelphotos/mari5.jpg', '/photos/reelphotos/mari5.webp', 'Nature''s Architect', 'Urban-Geometry-Project', 'urbangeometry-project', null, false, 4
where not exists (select 1 from reel_items where sort_order = 4);
insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)
select '/photos/reelphotos/mari6.jpg', '/photos/reelphotos/mari6.webp', 'Misty Blues', 'Portrait-Project', 'portrait-project', null, false, 5
where not exists (select 1 from reel_items where sort_order = 5);
insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)
select '/photos/reelphotos/mari7.jpg', '/photos/reelphotos/mari7.webp', 'Viva las Vegas', 'Fashion-Project', 'fashion-project', null, false, 6
where not exists (select 1 from reel_items where sort_order = 6);
insert into reel_items (url_jpg, url_webp, title, caption, target_slug, target_photo_index, is_narrow, sort_order)
select '/photos/reelphotos/mari2.jpg', '/photos/reelphotos/mari2.webp', 'Viva las Vegas', 'Fashion-Project', 'fashion-project', 2, true, 7
where not exists (select 1 from reel_items where sort_order = 7);

commit;
